@include ('templates\header')
<h1>Homepage</h1>
<p>
	This website is generated by actionIndex method in app\controllers\HomepageController.php class
</p>
<p>
	This method loads an app\views\homepage\index.php view.
</p>

<div>
	<p>Partial view test:</p>
	@include ('homepage\partialTest',['message'=>'Welcome to Foundation framework.']);
</div>
@include('templates\footer');
